
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:2001/eureka/
    register-with-eureka: false
    fetch-registry: true
  instance:
    hostname: localhost
spring:
  application:
    name: spring-cloud-eurekaconsumer
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
server:
  port: 2003
feign:
  httpclient:
    enabled: true
